product_key:
  - habitat-mac-bootstrapper

slack:
  notify_channel:
    - releng-notify

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
        - "Expeditor: Skip All"
  - built_in:trigger_omnibus_release_build:
      ignore_labels:
        - "Omnibus: Skip Build"
        - "Expeditor: Skip All"
      only_if: built_in:bump_version

artifact_actions:
  promoted_to_stable:
    - built_in:rollover_changelog
    - built_in:notify_chefio_slack_channels
